### ISSUE TITLE
docs site allows unencrypted access (http)

### ISSUE THREAD

**Issue by ductape** [rovercode/user-docs#3]
http://docs.rovercode.com/ allows users to view over plain HTTP without encryption. It seems the https redirect is not configured for docs subdomain. The marketing page (http://rovercode.com) is served over HTTPS with redirect.

**Comment by hbradio** [comment]
Just changed the CloudFront settings. Behavior should change sometime in the next 15 minutes.

**Comment by hbradio** [comment]
Seems to be redirecting now! I'll let you verify and close the ticket if it is.

**Comment by ductape** [comment]
On my first load, it loaded insecure, but I think that was a caching issue in my local browser. All subsequent loads and even typing `http` still redirect to `https` now. Thanks for the quick fix!
